# Generated by Django 4.2.13 on 2024-06-12 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SourceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Denominazione"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=250, null=True, verbose_name="Slug"
                    ),
                ),
            ],
            options={
                "verbose_name": "tipo di fonte",
                "verbose_name_plural": "tipi di fonte",
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Indicare l'istituzione (es. Cons. Reg. Lazio)",
                        max_length=512,
                        verbose_name="Denominazione della fonte",
                    ),
                ),
                ("url", models.URLField(max_length=1024)),
                (
                    "op_url",
                    models.URLField(
                        blank=True,
                        help_text="URL della pagina OP contenente le istituzioni",
                        null=True,
                    ),
                ),
                ("selector", models.CharField(blank=True, max_length=512)),
                (
                    "content",
                    models.TextField(
                        blank=True, null=True, verbose_name="Contenuto significativo"
                    ),
                ),
                ("timeout", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Note")),
                (
                    "is_verification_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Unset checkbox to disable verification",
                        verbose_name="Verification enabled",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last verification"
                    ),
                ),
                (
                    "verification_status",
                    models.IntegerField(
                        choices=[
                            (0, "Immutato"),
                            (1, "Cambiato"),
                            (2, "Errore rilevato"),
                            (3, "OP Aggiornato"),
                            (4, "Errore segnalato"),
                        ],
                        null=True,
                        verbose_name="Stato",
                    ),
                ),
                (
                    "verification_error",
                    models.TextField(blank=True, null=True, verbose_name="Errore"),
                ),
                (
                    "use_cleaner",
                    models.BooleanField(default=True, verbose_name="Utilizza cleaner"),
                ),
                (
                    "use_proxy",
                    models.BooleanField(default=True, verbose_name="Utilizza proxy IT"),
                ),
                (
                    "source_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="websourcemonitor.sourcetype",
                        verbose_name="Tipo di organizzazione",
                    ),
                ),
            ],
            options={
                "verbose_name": "contenuto",
                "verbose_name_plural": "contenuti",
            },
        ),
    ]
