# Generated by Django 4.2.13 on 2024-07-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("websourcemonitor", "0002_alter_content_verification_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="browser",
            field=models.CharField(
                choices=[("chrome", "chrome"), ("firefox", "Firefox")],
                default="chrome",
                verbose_name="Browser",
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="next_content",
            field=models.TextField(
                blank=True, null=True, verbose_name="Contenuto significativo nuovo"
            ),
        ),
    ]
