# Generated by Django 4.2.13 on 2024-07-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("websourcemonitor", "0003_content_browser_content_next_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="scraping_class",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
