from django.conf import settings
from .defaults import (
    DEFAULT_SLACK_TOKEN, DEFAULT_SLACK_CHANNEL,
    DEFAULT_SMTP_HOST, DEFAULT_SMTP_PORT, DEFAULT_SMTP_USE_TLS, DEFAULT_SMTP_USERNAME, DEFAULT_SMTP_PASSWORD,
    DEFAULT_EMAIL_SUBJECT_PREFIX, DEFAULT_EMAIL_FROM,
    DEFAULT_REQUESTS_MAX_TIMEOUT, DEFAULT_REQUESTS_UA,
    DEFAULT_PROXY_URL, DEFAULT_PROXY_USERNAME, DEFAULT_PROXY_PASSWORD, DEFAULT_USE_RQ
)

SLACK_TOKEN = getattr(settings, 'SLACK_TOKEN', DEFAULT_SLACK_TOKEN)
SLACK_CHANNEL = getattr(settings, 'SLACK_CHANNEL', DEFAULT_SLACK_CHANNEL)
SMTP_HOST = getattr(settings, 'SMTP_HOST', DEFAULT_SMTP_HOST)
SMTP_PORT = getattr(settings, 'SMTP_PORT', DEFAULT_SMTP_PORT)
SMTP_USE_TLS = getattr(settings, 'SMTP_USE_TLS', DEFAULT_SMTP_USE_TLS)
SMTP_USERNAME = getattr(settings, 'SMTP_USERNAME', DEFAULT_SMTP_USERNAME)
SMTP_PASSWORD = getattr(settings, 'SMTP_PASSWORD', DEFAULT_SMTP_PASSWORD)
EMAIL_SUBJECT_PREFIX = getattr(settings, 'EMAIL_SUBJECT_PREFIX', DEFAULT_EMAIL_SUBJECT_PREFIX)
EMAIL_FROM = getattr(settings, 'EMAIL_FROM', DEFAULT_EMAIL_FROM)
REQUESTS_MAX_TIMEOUT = getattr(settings, 'REQUESTS_MAX_TIMEOUT', DEFAULT_REQUESTS_MAX_TIMEOUT)
REQUESTS_UA = getattr(settings, 'REQUESTS_UA', DEFAULT_REQUESTS_UA)
PROXY_URL = getattr(settings, 'DEFAULT_PROXY_URL', DEFAULT_PROXY_URL)
PROXY_USERNAME = getattr(settings, 'PROXY_USERNAME', DEFAULT_PROXY_USERNAME)
PROXY_PASSWORD = getattr(settings, 'PROXY_PASSWORD', DEFAULT_PROXY_PASSWORD)
USE_RQ = getattr(settings, 'USE_RQ', DEFAULT_USE_RQ)
